[package]
authors = ["Eden <rust@eden2.com>"]
categories = ["database"]
description = "Easy local data persistence layer, backed by SQLite"
edition = "2018"
keywords = ["database", "sqlite", "sql"]
license = "MIT OR Apache-2.0"
name = "turbosql"
readme = "../README.md"
repository = "https://github.com/trevyn/turbosql"
version = "0.0.2"

[dependencies]
anyhow = "1"
directories-next = "2"
itertools = "0.10"
log = "0.4"
once_cell = "1.5"
rusqlite = {version = "0.24", features = ["bundled", "blob"]}
serde = {version = "1", features = ["derive"]}
toml = "0.5"
turbosql-impl = {path = "../turbosql-impl", version = "0.0.2"}

[dev-dependencies]
doc-comment = "0.3"
i54_ = {version = "0.0.1", features = ["rusqlite"]}

[features]
test = ["turbosql-impl/test"]

[[test]]
name = "integration_test"
path = "tests/integration_test.rs"
required-features = ["test"]
