name: ci

on:
  push:
  pull_request:
  schedule: [cron: '40 2 * * *']

env:
  CARGO_TERM_COLOR: always

jobs:
  checklinks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: lycheeverse/lychee-action@v1
        id: lychee
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --verbose --no-progress --headers="accept=text/html" "**/*.md" "**/*.rs" "**/*.json" "**/*.toml" "**/*.yml"

      - name: Fail if there were link-check errors
        run: exit ${{ steps.lychee.outputs.exit_code }}

  test:
    name: test rust ${{ matrix.rust }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [1.46, 1.47, stable, beta, nightly]
#              1.46 is minimum rustc version
    steps:
      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      
      - name: cargo test turbosql-impl
        run: cargo test --features "test" -- --nocapture
        working-directory: 'turbosql-impl'

      - name: cargo test turbosql
        run: cargo test --features "test" -- --nocapture
        working-directory: 'turbosql'

      - run: cargo doc --no-deps
