name: ci

on:
  push:
  pull_request:
  schedule: [cron: '40 2 * * *']

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test rust ${{ matrix.rust }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [1.46, stable, beta, nightly]
             # 1.46 is minimum rustc version
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      
      - name: cargo test turbosql-impl
        run: cargo test --features "test" -- --nocapture
        working-directory: 'turbosql-impl'

      - name: cargo test turbosql
        run: cargo test --features "test" -- --nocapture
        working-directory: 'turbosql'

      - run: cargo doc
